[build]
  base = "."
  command = "npm install && npm run build:client"
  publish = "dist/public"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./client/ ./public/"

[build.environment]
  NODE_VERSION = "20"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

  [functions.api]
    external_node_modules = ["cors", "express", "serverless-http", "firebase-admin"]

  [functions.categories]
    external_node_modules = ["cors", "express", "serverless-http", "firebase-admin"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
